<?php
/**
 * Created by PhpStorm.
 * User: lecongthang
 * Date: 29/11/2018
 * Time: 15:16
 */
return [
    'old_avatar_default_folder' => '/users/default-avatars',
    'old_avatar_folder' => '/files/users/avatars',
    'old_vocabulary_audio_folder' => '/files/vocabulary/audios',
    'old_vocabulary_audio_example_folder' => '/files/vocabulary/audios_example',
    'old_vocabulary_image_folder' => '/files/vocabulary/images',
    'old_course_image_folder' => '/files/courses/avatars',
    'old_course_video_folder' => '/files/courses/videos',
    'old_course_routes_folder' => '/files/courses/routes',
    'old_grammar_folder' => 'files/grammar/videos',
    'old_finder_folder' => 'finders/',
    'old_lessons_folder' => '/files/lessons/avatars',
    'old_kanji_audio_folder' => '/files/kanji/audios',
    'old_kanji_image_folder' => '/files/kanji/images',
    'old_conversation_media_folder' => '/files/conversation/medias',
    'old_conversation_image_folder' => '/files/conversation/images',
    'old_conversation_sub_title_folder' => '/files/conversation/sub-title',
    'old_question_media_folder' => '/files/question/medias',
    'old_question_image_folder' => '/files/question/images',
    'old_alphabet_image_folder' => '/files/alphabet/images',
    'old_alphabet_audio_folder' => '/files/alphabet/audio',
    'old_test_folder' => '/files/test/videos',
    'old_test_images_folder' => '/files/test/images',
    'old_test_package_image_folder' => '/files/test_package/images',
    'old_credit_image_folder' => '/files/credit/images',
    'old_slider_image_folder' => '/files/slider/images',
    'old_article_image_folder' => '/files/article/images',
    'old_config_image_folder' => '/files/config/images',
    'old_company_image_folder' => '/files/company/images',

    'avatar_default_folder' => 'users/default-avatars/',
    'avatar_folder' => 'users/avatars/',
    'vocabulary_audio_folder' => 'vocabulary/audios/',
    'vocabulary_audio_example_folder' => 'vocabulary/audios_example/',
    'vocabulary_image_folder' => 'vocabulary/images/',
    'course_image_folder' => 'courses/avatars/',
    'course_video_folder' => 'courses/videos/',
    'course_routes_folder' => 'courses/routes/',
    'grammar_folder' => 'grammar/videos/',
    'finder_folder' => 'finders/',
    'lessons_folder' => 'lessons/avatars/',
    'kanji_audio_folder' => 'kanji/audios/',
    'kanji_image_folder' => 'kanji/images/',
    'conversation_media_folder' => 'conversation/medias/',
    'conversation_image_folder' => 'conversation/images/',
    'conversation_sub_title_folder' => 'conversation/sub-title/',
    'question_media_folder' => 'question/medias/',
    'question_image_folder' => 'question/images/',
    'alphabet_image_folder' => 'alphabet/images/',
    'alphabet_audio_folder' => 'alphabet/audio/',
    'test_folder' => 'test/videos/',
    'test_images_folder' => 'test/images/',
    'test_package_image_folder' => 'test_package/images/',
    'credit_image_folder' => 'credit/images/',
    'slider_image_folder' => 'slider/images/',
    'article_image_folder' => 'article/images/',
    'article_cv_folder' => 'article/cvs/',
    'config_image_folder' => 'config/images/',
    'company_image_folder' => 'company/images/',
    'landing_page_image_folder' => 'landing_page/images/',
    'landing_page_video_folder' => 'landing_page/videos/',
];
